---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: av-bill-webappdeployment
spec:
   replicas: 1
   strategy:
     type: Recreate
   selector:
     matchLabels:
       app: av-bill-webapp
   template:
     metadata:
       name: av-bill-webapppod
       labels:
        app: av-bill-webapp
     spec:
       containers:
      - name: av-bill-webappcontainer
        image: vaishnavi062/av-bill-webapp
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
   name: av-bill-webappsvc
spec:
   type: NodePort
   selector:
    app: av-bill-webapp
   ports:
   - port: 80
     targetPort: 8080

...
